export type Book = "PHB" | "ToM" | "S&M" | string
export type Save = "Negate" | "None" | "1/2" | "Special"
export type Caster = "Wizard" | "Cleric"
export type School =
  | "Abjuration"
  | "Alteration"
  | "Conjuration"
  | "Diviniation"
  | "Enchantment"
  | "Invocation"
  | "Illusion"
  | "Necromancy"

export type Sphere =
  | "All"
  | "Animal"
  | "Astral"
  | "Chaos"
  | "Charm"
  | "Combat"
  | "Creation"
  | "Divination"
  | "Elemental"
  | "Guardian"
  | "Healing"
  | "Law"
  | "Necromantic"
  | "Numbers"
  | "Plant"
  | "Protection"
  | "Summoning"
  | "Sun"
  | "Thought"
  | "Travelers"
  | "War"
  | "Wards"
  | "Weather"
